- hosts: localhost
  become: yes
  tasks:
  - name: debug info
    debug: var=ansible_env.HOME

  - name: Install apt packages
    apt:
      update_cache: yes
      name:
        - astyle
        - binutils
        - bpython
        - byobu
        - cmake
        - curl
        - docker
        - g++
        - git
        - golang
        - google-perftools
        - kcachegrind
        - lcov
        - libboost-all-dev
        - libgoogle-perftools-dev
        - libicu-dev
        - libncurses-dev
        - net-tools
        - nmap
        - openssh-server
        - pv
        - python-dev
        - silversearcher-ag
        - subversion
        - tig
        - vim-gtk

  - name: Install Go
    shell: |
      [ -d /usr/local/go ] && echo 'Go is already installed' && exit 0
      VERSION=1.15
      OS=linux
      ARCH=amd64
      sudo curl https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz | tar -C /usr/local -xz
    register: result
    changed_when: "'Go is already installed' not in result.stdout"

  - name: Install docker
    shell: |
      docker --version && exit 0
      sudo apt-get update
      sudo apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo apt-key fingerprint 0EBFCD88
      sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    register: result
    changed_when: "'Docker' not in result.stdout"

- hosts: localhost
  become_user: yasukei
  tasks:
  - name: debug info
    debug: var=ansible_env.HOME

  - name: Make symbolic link for dotfiles
    file:
      src: "~/git/dotfiles/dotfiles/{{ item }}"
      dest: "~/{{ item }}"
      state: link
    loop:
      - .astylerc
      - .ctags
      - .gitconfig
      - .gitignore
      - _gvimrc
      - .tigrc
      - .vim
      - .vimrc

  - name: Install dein.vim
    shell: |
      [ -d ~/.cache/dein ] && echo 'dein.vim is already installed' && exit 0
      curl -o installer.sh https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh &&
      sh ./installer.sh ~/.cache/dein &&
      rm ./installer.sh
    register: result
    changed_when: "'dein.vim is already installed' not in result.stdout"

  - name: Install fzf
    shell: |
      [ -d ~/.fzf ] && echo 'fzf is already installed' && exit 0
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
      ~/.fzf/install
    register: result
    changed_when: "'fzf is already installed' not in result.stdout"

  - name: Install GNU Global
    shell: |
      TARGET=global-6.6.5
      [ -f ~/bin/"$TARGET"/INSTALLED_BY_ANSIBLE ] && echo 'GNU Global is already installed' && exit 0
      mkdir -p ~/bin
      cd ~/bin &&
      curl ftp://ftp.gnu.org/pub/gnu/global/"$TARGET".tar.gz > "$TARGET".tar.gz &&
      tar xzf "$TARGET".tar.gz &&
      cd "$TARGET" &&
      ./configure &&
      sudo make install &&
      cp gtags.vim ~/.vim/plugin/ &&
      touch INSTALLED_BY_ANSIBLE
    register: result
    changed_when: "'GNU Global is already installed' not in result.stdout"

  - name: Make Go environment. Prepare environment variables
    blockinfile:
      path: "~/.profile"
      insertafter: EOF
      block: |
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=~/go

  - name: Make Go environment. Create a directory
    file:
      path: ~/go/src/github.com/{{ ansible_env.USER }}
      state: directory

