- hosts: localhost
  #become: yes
  tasks:
  - name: install apt packages
    apt:
      update_cache: yes
      name:
        - astyle
        - binutils
        - bpython
        - byobu
        - cmake
        - curl
        - g++
        - git
        - golang
        - google-perftools
        - kcachegrind
        - lcov
        - libboost-all-dev
        - libgoogle-perftools-dev
        - libicu-dev
        - libncurses-dev
        - net-tools
        - nmap
        - openssh-server
        - pv
        - python-dev
        - silversearcher-ag
        - subversion
        - tig
        - vim-gtk

  - name: make symbolic link for dotfiles
    file:
      src: "/home/yasukei/git/dotfiles/dotfiles/{{ item }}"
      dest: "/home/yasukei/{{ item }}"
      state: link
    loop:
      - .astylerc
      - .ctags
      - .gitconfig
      - .gitignore
      - _gvimrc
      - .tigrc
      - .vim
      - .vimrc

  - name: Insert environment variables to .profile
    blockinfile:
      path: "/home/yasukei/.profile"
      insertafter: EOF
      block: |
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=~/go

