- hosts: localhost
  become: yes
  tasks:
  - name: debug info
    debug: var=ansible_env.HOME

  - name: Install apt packages
    apt:
      update_cache: yes
      name:
        - astyle
        - binutils
        - bpython
        - byobu
        - cmake
        - curl
        - g++
        - git
        - golang
        - google-perftools
        - kcachegrind
        - lcov
        - libboost-all-dev
        - libgoogle-perftools-dev
        - libicu-dev
        - libncurses-dev
        - net-tools
        - nmap
        - openssh-server
        - pv
        - python-dev
        - silversearcher-ag
        - subversion
        - tig
        - vim-gtk

  - name: Install Go
    shell: |
      [ -d /usr/local/go ] && exit 0
      VERSION=1.15
      OS=linux
      ARCH=amd64
      sudo curl https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz | tar -C /usr/local -xz

- hosts: localhost
  become_user: yasukei
  tasks:
  - name: debug info
    debug: var=ansible_env.HOME

  - name: Make symbolic link for dotfiles
    file:
      src: "~/git/dotfiles/dotfiles/{{ item }}"
      dest: "~/{{ item }}"
      state: link
    loop:
      - .astylerc
      - .ctags
      - .gitconfig
      - .gitignore
      - _gvimrc
      - .tigrc
      - .vim
      - .vimrc

  - name: Install dein.vim
    shell: |
      [ -d ~/.cache/dein ] && exit 0
      curl -o installer.sh https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh &&
      sh ./installer.sh ~/.cache/dein &&
      rm ./installer.sh

  - name: Install fzf
    shell: |
      [ -d ~/.fzf ] && exit 0
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
      ~/.fzf/install

  - name: Install GNU Global
    shell: |
      TARGET=global-6.6.5
      [ -f ~/bin/"$TARGET"/INSTALLED_BY_ANSIBLE ] && exit 0
      mkdir -p ~/bin
      cd ~/bin &&
      curl ftp://ftp.gnu.org/pub/gnu/global/"$TARGET".tar.gz > "$TARGET".tar.gz &&
      tar xzf "$TARGET".tar.gz &&
      cd "$TARGET" &&
      ./configure &&
      sudo make install &&
      cp gtags.vim ~/.vim/plugin/ &&
      touch INSTALLED_BY_ANSIBLE

  - name: Make Go environment. Prepare environment variables
    blockinfile:
      path: "~/.profile"
      insertafter: EOF
      block: |
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=~/go

  - name: Make Go environment. Create a directory
    file:
      path: ~/go/src/github.com/{{ ansible_env.USER }}
      state: directory

